In [1]:
import numpy as np

x = np.nan
print(x == np.nan)
print(x is np.nan)
print(np.isnan(x))
print(~np.isnan(x))

False
True
True
False


In [3]:
import numpy as np

x = np.array([1.0, 2, np.nan, -2e3, np.nan, 7e333])  # Just an array with some NaN's
print("x=                       ", x)
print("isnan(x)=                ", np.isnan(x))
print("The indices where True :", np.where(np.isnan(x))[0])   

x=                        [ 1.e+00  2.e+00     nan -2.e+03     nan     inf]
isnan(x)=                 [False False  True False  True False]
The indices where True : [2 4]


In [8]:
import numpy as np
x= np.array([3,4,2,np.nan,3,2.0,-1])
idx_max = np.argmax(x) #Gives the index of 1st nan encountered'''
idx_nanargmax = np.nanargmax(x) #Ignores all Nan to find the true max'''
print (idx_argmax)
print (idx_nanargmax)

3
1


In [14]:
import numpy as np

counts = np.array([123432, np.nan, 22333, 344433, np.inf, 222222])

#part 1
filter_mask = np.isfinite(counts)
filtered_counts = counts[filter_mask]
print("Filtered Array:", filtered_counts)

#part 2
masked_counts = np.ma.masked_invalid(counts)

print("Masked Array:")
print(masked_counts)

Filtered Array: [123432.  22333. 344433. 222222.]
Masked Array:
[123432.0 -- 22333.0 344433.0 -- 222222.0]


In [17]:
x = 2.2
y = 3.1
z0 = 2.2 + 3.1j
z1 = complex(x,y)
z2 = x + y*1j                       # yj or y*j will not work
print(f"z0={z0}, z1={z1}, z2={z2}")

z0=(2.2+3.1j), z1=(2.2+3.1j), z2=(2.2+3.1j)


In [18]:
import numpy as np
z = np.arange(10, dtype='complex')
print(z)
print(z.real)
print(z.imag)

#Continue from 14.2 creating complex no. arrays using numpy

[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
import numpy as np
z= 6+7j
length = np.abs(z)
print ("Length of vector :",length)
degs = np.angle(z,deg=True)
print (degs,"degrees")
print ("z is complex?", np.iscomplex(z))
print(f"3 times z is : =,{3*z}")

def polar2complex(lengths, angles):
    """Convert length and angle to a complex number.
       The function arguments can be NumPy arrays"""
    return lengths * np.exp(1j*angles)

angle = np.radians(degs)
z = polar2complex(length, angle)
print(f"z={z:.1f}")
    

Length of vector : 9.219544457292887
49.398705354995535 degrees
z is complex? True
3 times z is : =,(18+21j)
z=6.0+7.0j


In [5]:
def scaling(value, bscale=1, bzero=0):
    """ Scale a value with bscale and add offset bzero"""
    result1 = bscale*value + bzero
    result2 = bscale * value
    return result1, result2

val = 3
r1, r2 = scaling(val, 2, 0.01)
print(r1, r2)

6.01 6


In [1]:
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits

data = fits.open('APOGEE_stars.fits')[1].data
print(data[0]) # The first row of the catalogue
print(data['STARFLAG']) # List all rows in the column of "STARFLAG"
print(data['STARFLAG'][:10]) # Print the first 10 elements in the column of "STARFLAG"
print(data['STARFLAG'][-10:]) # Print the last 10 elements in the column of "STARFLAG"

(nan, nan, nan, nan, nan, 133, 0, 418.9276)
[   0 3072    0 ... 2052    0  516]
[       0     3072        0      512        0        0        0        0
 50331652     1536]
[       0 50331652        0     2048        0  2097152     3072     2052
        0      516]
