In [2]:
f= open("5 Galaxy names", 'w')
f.write("Milky Way\n")
f.write("Andromeda\n")
f.write("India\n")
f.write("Netherlands\n")
f.write("France")
f.close()

In [4]:
#5.1
clusters = [
    "Virgo Cluster",
    "Fornax Cluster",
    "Hercules Cluster",
    "Coma Cluster",
    "Norma Cluster"
]

file_name = "galaxy_clusters.txt"

with open(file_name, "w") as f:
    for cluster in clusters:
        f.write(cluster + "\n")
        
with open(file_name, "r") as file:
    for i, line in enumerate(file, 1):
        names = line.strip()
        print(f"Galaxy cluster {i} is {names}")
f.close()

Galaxy cluster 1 is Virgo Cluster
Galaxy cluster 2 is Fornax Cluster
Galaxy cluster 3 is Hercules Cluster
Galaxy cluster 4 is Coma Cluster
Galaxy cluster 5 is Norma Cluster


In [6]:
s = """# Rotation curve for NGC1234
# Tilted ring parameters
#   radius       width     density   error
    10.0         1.0       23.456    0.23
    15.0         1.0       27.898    0.34
    20.0         1.0       26.883    0.29
    25.0         1.5       46.399    4.23
    30.0         1.5       51.422    4.44
    35.0         1.5       53.289    4.52
"""
from pathlib import Path
import os

tilde_path = os.path.expanduser('~')
subdirectory = 'Downloads'
filename = 'myfile.txt'

OSpath = f"{tilde_path}/{subdirectory}/{filename}"
path = Path(OSpath)
print("Composed path:", path)
path = Path(f"{tilde_path}/{subdirectory}/mydata1.txt")

f = open(path, 'w')
f.write(s)
f.close()

Composed path: /Users/users/dshah/Downloads/myfile.txt


In [14]:
#5.4
import numpy as np
A = np.zeros((5, 4))
B = np.arange(6).reshape(3, 2) + 10

print("Initial A:\n", A)
print("\nArray B:\n", B)
A[1:4, 1:3] = B

print("\nFinal A after replacement:\n", A)

Initial A:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array B:
 [[10 11]
 [12 13]
 [14 15]]

Final A after replacement:
 [[ 0.  0.  0.  0.]
 [ 0. 10. 11.  0.]
 [ 0. 12. 13.  0.]
 [ 0. 14. 15.  0.]
 [ 0.  0.  0.  0.]]


In [16]:
#5.5
import numpy as np
M = np.arange(60).reshape(3, 4, 5)
print("M:\n", M)

print("\nElement corresponding to 33:", M[1, 2, 3])
print(np.where(M==33))


M:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

Element corresponding to 33: 33
(array([1]), array([2]), array([3]))
